# ocws - opencode workspace. Creates a jj workspace for a single agent,
# claims it with a change description, and starts opencode rooted there, then
# reclaims finished workspaces. jj workspaces are the shared-repo equivalent
# of git worktrees and are the supported way to run parallel agents against
# one repository.
#
# Base directory precedence: $OCWS_BASE, then the parent directory of the
# current workspace (the sibling convention) when writable, then
# $XDG_DATA_HOME/ocws (default ~/.local/share/ocws) so workspaces survive
# reboots without ever needing root, then /tmp/opencode. The workspace
# directory is "<base>/nixos-ws-<task>".
#
# OCWS_V2=1 starts opencode 2 (opencode2) with the isolated V2 config
# generated by the opencode v2 module.
#
# OCWS_HOOK_{PRE,POST}_{CREATE,DELETE} run a shell command around workspace
# creation and removal for per-workspace setup/teardown (dev ports, .env
# files, caches). OCWS_TASK/DIR/ROOT/BASE are exported to the hook.
{
  writeShellApplication,
  jujutsu,
  coreutils,
  gnugrep,
  rip2,
  zellij,
  bash,
}:
writeShellApplication {
  name = "ocws";
  runtimeInputs = [
    jujutsu
    coreutils
    gnugrep
    rip2
    zellij
    bash
  ];
  text = ''
    set -euo pipefail

    usage() {
      cat >&2 <<'USAGE'
    Usage:
      ocws <task> [-- <opencode args>...]   create a workspace and run opencode there
      ocws tab <task> [-- <opencode args>]  create a workspace in a new zellij tab
      ocws ls                               list workspaces and their claims (never mutates a working copy)
      ocws done <task>                      remove a finished workspace (refuses unmerged work)
      ocws rm [--force] <task>              remove a workspace; --force discards unmerged work
      ocws gc                               remove finished workspaces idle past OCWS_GC_AGE

    Environment:
      OCWS_BASE     directory holding workspace directories (default: beside the repo
                    when writable, else ~/.local/share/ocws, else /tmp/opencode)
      OCWS_V2=1     run opencode 2 (opencode2) with the isolated V2 config
      OCWS_GC_AGE   seconds an empty, finished workspace must sit idle before gc
                    removes it (default 86400)
      OCWS_HOOK_PRE_CREATE / OCWS_HOOK_POST_CREATE / OCWS_HOOK_PRE_DELETE /
      OCWS_HOOK_POST_DELETE
                    optional shell commands run around workspace create/remove,
                    with OCWS_TASK/DIR/ROOT/BASE exported
    USAGE
      exit 2
    }

    root="$(jj workspace root 2>/dev/null)" || {
      echo "ocws: not inside a jj workspace" >&2
      exit 1
    }

    base="''${OCWS_BASE:-}"
    if [ -z "$base" ]; then
      candidate="$(dirname "$root")"
      if [ -w "$candidate" ]; then
        base="$candidate"
      else
        base="''${XDG_DATA_HOME:-$HOME/.local/share}/ocws"
        mkdir -p "$base"
      fi
    fi
    if [ ! -w "$base" ]; then
      base=/tmp/opencode
    fi
    mkdir -p "$base"

    valid_task() { printf '%s' "$1" | grep -Eq '^[A-Za-z0-9][A-Za-z0-9._-]*$'; }
    ws_dir_for() { printf '%s/nixos-ws-%s' "$base" "$1"; }
    # Workspace listings and the finished-work check are read-only and must
    # never snapshot a foreign working copy: an `ocws ls` run from the primary
    # or another session's workspace would otherwise fold that workspace's
    # uncommitted changes into its @.
    workspace_exists() {
      local names
      names="$(jj --ignore-working-copy workspace list -T 'name ++ "\n"' 2>/dev/null)"
      grep -qx "$1" <<<"$names"
    }
    # A revision is absorbed when every file it touches already has its content
    # on main@origin: a squash-merge replaces the draft commit but lands the
    # same bytes, so the draft is finished even though it is not an ancestor.
    # Pure jj, so it also works in a secondary workspace, which has no .git.
    ws_commit_absorbed() {
      local cid="$1" f
      for f in $(jj --ignore-working-copy diff -r "$cid" --name-only 2>/dev/null); do
        if [ -n "$(jj --ignore-working-copy diff --from 'main@origin' --to "$cid" -- "$f" 2>/dev/null)" ]; then
          return 1
        fi
      done
      return 0
    }
    # A workspace "has work" when any commit reachable from its @ lies outside
    # main@origin and is not fully absorbed there. Checking absorption per
    # revision lets done/gc reclaim a workspace whose PR squash-merged, which -
    # unlike a fast-forward - leaves the draft commit off main@origin. Only
    # snapshotted commits are visible: a foreign workspace is never snapshotted
    # (that would fold a live session's edits into its @), so unsnapshotted
    # edits are invisible here and rip's graveyard is the recovery net.
    ws_has_work() {
      local rev="$1@" cid
      for cid in $(jj --ignore-working-copy log --no-graph -r "ancestors($rev) ~ ::main@origin ~ empty()" -T 'commit_id ++ "\n"' 2>/dev/null); do
        ws_commit_absorbed "$cid" || return 0
      done
      return 1
    }
    # Optional lifecycle hook, run with `bash -c` and OCWS_TASK/DIR/ROOT/BASE
    # exported. Env-only so there is no config file to parse. A failing hook is
    # warned about, not fatal: a broken setup step must not strand a workspace
    # or block gc.
    run_hook() {
      local hook="$1" task="$2" dir="$3" cmd="$4"
      [ -n "$cmd" ] || return 0
      OCWS_TASK="$task" OCWS_DIR="$dir" OCWS_ROOT="$root" OCWS_BASE="$base" \
        bash -c "$cmd" || echo "ocws: '$hook' hook failed" >&2
    }
    rip_workspace() {
      local task="$1" dir
      dir="$(ws_dir_for "$task")"
      if [ "$(realpath -m "$dir")" = "$(realpath -m "$root")" ]; then
        echo "ocws: refusing to remove the current workspace ('$task')" >&2
        exit 1
      fi
      run_hook pre_delete "$task" "$dir" "''${OCWS_HOOK_PRE_DELETE:-}"
      jj workspace forget "$task"
      [ -d "$dir" ] && rip "$dir"
      run_hook post_delete "$task" "$dir" "''${OCWS_HOOK_POST_DELETE:-}"
    }
    # Forget+rip workspaces whose work is finished (nothing outside
    # main@origin that is not absorbed) and that have been idle for at least
    # OCWS_GC_AGE seconds, never the current one. An active session touches its
    # directory as it works, so idle time separates abandoned workspaces from
    # live ones; rip's graveyard makes a mistaken removal restorable.
    ocws_gc() {
      local name dir age now
      now="$(date +%s)"
      for name in $(jj --ignore-working-copy workspace list -T 'name ++ "\n"' 2>/dev/null); do
        [ "$name" = "default" ] && continue
        dir="$base/nixos-ws-$name"
        [ -d "$dir" ] || continue
        [ "$(realpath -m "$dir")" = "$(realpath -m "$root")" ] && continue
        age="$((now - $(stat -c %Y "$dir" 2>/dev/null || echo "$now")))"
        [ "$age" -ge "''${OCWS_GC_AGE:-86400}" ] || continue
        if ws_has_work "$name"; then
          echo "ocws gc: keeping '$name' (unmerged work)"
          continue
        fi
        rip_workspace "$name"
        echo "ocws gc: forgot '$name' (finished)"
      done
    }

    sub="''${1:-}"
    [ -n "$sub" ] || usage

    # Optional leading flag: run the opencode 2 beta instead of V1.
    if [ "$sub" = "--v2" ]; then
      OCWS_V2=1
      shift
      sub="''${1:-}"
      [ -n "$sub" ] || usage
    fi

    case "$sub" in
      ls|list)
        shift
        jj --ignore-working-copy workspace list
        echo ""
        echo "Claims (working copies):"
        jj --ignore-working-copy log --no-graph -r 'working_copies()' -T 'change_id.short() ++ "  " ++ description.first_line() ++ "\n"'
        exit 0
        ;;
      gc)
        shift
        ocws_gc
        exit 0
        ;;
      done)
        shift
        task="''${1:-}"
        [ -n "$task" ] || usage
        valid_task "$task" || { echo "ocws: invalid task '$task'" >&2; exit 2; }
        workspace_exists "$task" || { echo "ocws: no workspace named '$task'" >&2; exit 1; }
        jj git fetch >/dev/null 2>&1 || true
        if ws_has_work "$task"; then
          echo "ocws: '$task' still has unmerged/uncommitted work; refusing to remove." >&2
          jj --ignore-working-copy log --no-graph -r "ancestors($task@) ~ ::main@origin ~ empty()" -T '"  " ++ commit_id.short() ++ " " ++ description.first_line() ++ "\n"' >&2
          echo "Merge the PR, then retry; or 'ocws rm --force $task' to discard." >&2
          exit 1
        fi
        rip_workspace "$task"
        echo "Done: forgot '$task' (directory sent to the graveyard)."
        exit 0
        ;;
      rm|forget)
        shift
        force=0
        if [ "''${1:-}" = "--force" ]; then force=1; shift; fi
        task="''${1:-}"
        [ -n "$task" ] || usage
        valid_task "$task" || { echo "ocws: invalid task '$task'" >&2; exit 2; }
        workspace_exists "$task" || { echo "ocws: no workspace named '$task'" >&2; exit 1; }
        if [ "$force" != "1" ] && ws_has_work "$task"; then
          echo "ocws: '$task' has unmerged/uncommitted work; use 'ocws done $task' after merging, or 'ocws rm --force $task' to discard." >&2
          exit 1
        fi
        rip_workspace "$task"
        echo "Forgot '$task' (directory sent to the graveyard)."
        exit 0
        ;;
      tab)
        new_tab=1
        shift
        ;;
      *)
        new_tab=0
        ;;
    esac

    task="''${1:-}"
    [ -n "$task" ] || usage
    shift || true
    [ "''${1:-}" = "--" ] && shift
    valid_task "$task" || { echo "ocws: invalid task '$task' (use [A-Za-z0-9._-])" >&2; exit 2; }

    dir="$(ws_dir_for "$task")"
    if workspace_exists "$task"; then
      echo "ocws: workspace '$task' already exists - 'ocws rm $task' to recreate it" >&2
      exit 1
    fi
    [ -e "$dir" ] && { echo "ocws: path already exists: $dir" >&2; exit 1; }

    # Opportunistically reclaim finished workspaces before adding a new one.
    # Best-effort: a gc failure must never block workspace creation.
    ocws_gc || true

    run_hook pre_create "$task" "$dir" "''${OCWS_HOOK_PRE_CREATE:-}"

    jj git fetch >/dev/null 2>&1 || true
    jj workspace add "$dir" --name "$task" -r 'main@origin' -m "$task: started from main@origin"

    run_hook post_create "$task" "$dir" "''${OCWS_HOOK_POST_CREATE:-}"

    if [ "''${OCWS_V2:-0}" = "1" ]; then
      # opencode2 resolves its own config root (the shim exports
      # OPENCODE_CONFIG_DIR) and its own database (opencode.db under the data
      # dir, shared with the TUI and the web service). Overriding either here
      # split V2 sessions into a second config root and the stale
      # opencode2.db, so a plain `opencode2` and an OCWS_V2=1 workspace never
      # saw each other's sessions.
      run=(opencode2 "$@")
    else
      run=(opencode "$@")
    fi

    if [ "$new_tab" = "1" ]; then
      if [ -z "''${ZELLIJ_SESSION_NAME:-}" ]; then
        echo "ocws: 'tab' must run inside a zellij session" >&2
        exit 1
      fi
      zellij action new-tab --name "$task" --cwd "$dir" -- "''${run[@]}"
    else
      cd "$dir"
      exec "''${run[@]}"
    fi
  '';
}
