{
 "title": "Fritz!Exporter",
 "description": "Demo Dashboard for stats from fritz_exporter (https://github.com/pdreker/fritzbox_exporter)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "label_values(fritz_uptime_seconds_total, friendly_name)"
    }
   },
   {
    "name": "wifi",
    "label": "WiFi Network",
    "query": {
     "query": "label_values(fritz_wifi_status, wifi_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "WAN Link Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_wan_phys_link_status{friendly_name=\"$device\"}"
    }
   ]
  },
  {
   "title": "PPP Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_ppp_connection_state{friendly_name=\"$device\"}"
    }
   ]
  },
  {
   "title": "PPP Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_ppp_connection_uptime_seconds_total{friendly_name=\"$device\"}"
    }
   ]
  },
  {
   "title": "LAN Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_lan_status{friendly_name=\"$device\"}"
    }
   ]
  },
  {
   "title": "LAN Enabled",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_lan_status_enabled{friendly_name=~\"$device\"}"
    }
   ]
  },
  {
   "title": "Update available",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_update_available{friendly_name=\"$device\"}"
    }
   ]
  },
  {
   "title": "Known Devices",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_known_devices_count{friendly_name=\"$device\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(fritz_uptime_seconds_total{friendly_name=\"$device\"}) without(softwareversion)"
    }
   ]
  },
  {
   "title": "Transfer last 365d",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(fritz_wan_data_bytes_total[365d])) without(pod, instance)",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Transfer last 30d",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(fritz_wan_data_bytes_total[30d])) without(pod, instance)",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Transfer last 7d",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(fritz_wan_data_bytes_total[7d])) without(pod, instance)",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Transfer last 24h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(fritz_wan_data_bytes_total[24h])) without(pod, instance)",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  { "title": "LAN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "LAN bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg(irate(fritz_lan_data_bytes_total{friendly_name=\"$device\"}[10m])) without(pod,instance)",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "LAN packet/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(irate(fritz_lan_packet_count_total{friendly_name=\"$device\"}[10m])) without(pod, instance)",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  { "title": "Wifi", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Wifi Enabled",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_wifi_status{friendly_name=~\"$device\", wifi_name=\"$wifi\"}",
     "legendFormat": "{{ enabled }}"
    }
   ]
  },
  {
   "title": "SSID",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_wifi_status{friendly_name=~\"$device\", wifi_name=\"$wifi\"}",
     "legendFormat": "{{ ssid }}"
    }
   ]
  },
  {
   "title": "Channel",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_wifi_channel{friendly_name=~\"$device\", wifi_name=\"$wifi\"}"
    }
   ]
  },
  {
   "title": "Packets/s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(irate(fritz_wifi_packets_count_total{friendly_name=\"$device\", wifi_name=\"$wifi\"}[10m])) without(pod,instance)",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "Associations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(fritz_wifi_associations_count{friendly_name=\"$device\", wifi_name=\"$wifi\"}) without(pod,instance)",
     "legendFormat": "associations"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_wifi_status{friendly_name=~\"$device\", wifi_name=\"$wifi\"}"
    }
   ]
  },
  {
   "title": "Associations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_wifi_associations_count{friendly_name=~\"$device\", wifi_name=\"$wifi\"}"
    }
   ]
  },
  {
   "title": "Wifi standard",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_wifi_status{friendly_name=~\"$device\", wifi_name=\"$wifi\"}",
     "legendFormat": "802.11{{ standard }}"
    }
   ]
  },
  { "title": "WAN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "WAN bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg(irate(fritz_wan_data_bytes_total{friendly_name=\"$device\"}[10m])) without(pod,instance)",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "WAN packet/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(irate(fritz_wan_data_packets_count_total{friendly_name=\"$device\"}[10m])) without(pod,instance)",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  { "title": "WAN Sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "WAN bitrate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_wan_datarate_bytes{friendly_name=\"$device\"}",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "WAN max sync",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fritz_wan_max_bitrate_bps{friendly_name=\"$device\"}",
     "legendFormat": "{{ direction }}"
    }
   ]
  }
 ]
}