# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
      kernelModules = ["amdgpu"];
      supportedFilesystems = ["zfs"];
    };
    kernelModules = ["amdgpu" "kvm-amd"];
    extraModulePackages = [];
  };

  fileSystems = {
    "/" = {
      device = "rpool/eyd/root";
      fsType = "zfs";
      neededForBoot = true;
    };

    "/nix" = {
      device = "rpool/eyd/nix";
      fsType = "zfs";
      neededForBoot = true;
    };

    "/per" = {
      device = "rpool/eyd/per";
      fsType = "zfs";
      neededForBoot = true;
    };

    "/home" = {
      device = "rpool/eyd/home";
      fsType = "zfs";
      neededForBoot = true;
    };

    "/boot" = {
      device = lib.mkDefault "/dev/disk/by-label/boot";
      fsType = "vfat";
      options = ["fmask=0022" "dmask=0022"];
      neededForBoot = true;
    };

    "/per/mnt/2tb-ssd" = {
      device = "/dev/sda1";
      fsType = "ext4";
    };
  };

  # Swap disabled - ZFS ZVOL swap can cause deadlocks and performance issues
  # ZFS's copy-on-write nature conflicts with swap's low-overhead expectations
  # causing memory allocation loops during low-memory situations.
  # Use zramSwap (configured system-wide) or dedicated partitions instead.
  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking = {
    useDHCP = lib.mkDefault true;
    # interfaces = {
    #   eno1.useDHCP = lib.mkDefault true;
    #   enp34s0.useDHCP = lib.mkDefault true;
    #   wlp38s0.useDHCP = lib.mkDefault true;
    # };
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
