# Shared stasis configuration
# Modern Wayland idle manager with media detection
# This prevents conflicts when multiple WM modules are imported
{
  lib,
  config,
  pkgs,
  inputs,
  ...
}: let
  niriEnabled = config.wm.niri.enable or false;
  hyprlandEnabled = config.wm.hyprland.enable or false;
  cosmicEnabled = config.programs.cosmic-session or {} != {};

  # Use graphical-session.target which is the standard for all Wayland compositors
  systemdTarget = "graphical-session.target";

  # Only enable if at least one WM is enabled
  shouldEnable = niriEnabled || hyprlandEnabled || cosmicEnabled;

  # RUNE configuration content
  runeConfig = ''
    # Stasis configuration - Wayland idle manager
    # Generated by NixOS configuration

    # Monitor media playback to prevent idle during video/audio
    monitor_media true

    # Respect Wayland idle inhibitor protocol
    respect_idle_inhibitors true

    # Ignore remote media sources (e.g., Spotify Connect, KDEConnect)
    ignore_remote_media true

    # Blacklist: apps that should NOT prevent idle
    media_blacklist [
      "spotify"
      "Music Player Daemon"
    ]
  '';

  stasisPackage = inputs.stasis.packages.${pkgs.stdenv.hostPlatform.system}.stasis;

  # Toggle script with OSD notification via wired/notify-send
  stasisToggle = pkgs.writeShellApplication {
    name = "stasis-toggle";
    runtimeInputs = with pkgs; [systemd libnotify];
    text = ''
      if systemctl --user is-active --quiet stasis; then
        # Notify first (stop can take time if stasis doesn't handle SIGTERM)
        notify-send -a "stasis" -u low -t 2000 -i preferences-desktop-screensaver \
          "Idle Inhibitor Disabled" \
          "System will idle normally"
        systemctl --user stop stasis &
      else
        systemctl --user start stasis
        notify-send -a "stasis" -u low -t 2000 -i caffeine-cup-full \
          "Idle Inhibitor Active" \
          "System will not idle while media is playing"
      fi
    '';
  };

  # Status script for ironbar (outputs JSON with icon based on state)
  stasisStatus = pkgs.writeShellApplication {
    name = "stasis-status";
    runtimeInputs = with pkgs; [systemd];
    text = ''
      if systemctl --user is-active --quiet stasis; then
        echo '{"text": "󰒳", "tooltip": "Idle inhibitor active - click to disable", "class": "active"}'
      else
        echo '{"text": "󰒲", "tooltip": "Idle inhibitor disabled - click to enable", "class": "inactive"}'
      fi
    '';
  };
in {
  config = lib.mkIf shouldEnable {
    # Add stasis package and helper scripts to user environment
    home.packages = [
      stasisPackage
      stasisToggle
      stasisStatus
    ];

    # Generate RUNE configuration file
    home.file.".config/stasis/stasis.rune".text = runeConfig;

    # Create systemd user service
    systemd.user.services.stasis = {
      Unit = {
        Description = "Stasis - Wayland idle manager with media detection";
        PartOf = [systemdTarget];
        After = [systemdTarget];
      };

      Service = {
        Type = "simple";
        ExecStart = "${stasisPackage}/bin/stasis";
        Restart = "on-failure";
        RestartSec = "5s";
        # Stasis doesn't handle SIGTERM properly, force quick shutdown
        TimeoutStopSec = 2;
      };

      Install = {
        WantedBy = [systemdTarget];
      };
    };
  };
}
