{
  config,
  lib,
  pkgs,
  ...
}:
with lib; let
  cfg = config.modules.system.backup;
in {
  options.modules.system.backup = {
    enable = mkEnableOption "system backup configuration";

    scripts = {
      wslBackup = mkOption {
        type = types.path;
        default = ../../tools/scripts/wsl-backup-hpprobook.sh;
        description = "Path to WSL backup script";
      };

      powershellOrchestrator = mkOption {
        type = types.path;
        default = ../../tools/scripts/WSL-Backup-Orchestrator.ps1;
        description = "Path to PowerShell orchestration script";
      };
    };

    schedule = {
      enable = mkEnableOption "automatic backup scheduling via systemd timer";

      frequency = mkOption {
        type = types.str;
        default = "daily";
        description = "Backup frequency (systemd timer format)";
      };

      time = mkOption {
        type = types.str;
        default = "02:00";
        description = "Time to run backup (HH:MM format)";
      };
    };

    backupDir = mkOption {
      type = types.str;
      default = "D:/Backups/WSL-NixOS";
      description = "Backup destination directory (Windows path)";
    };

    retention = {
      fullBackups = mkOption {
        type = types.int;
        default = 3;
        description = "Number of full VHDX exports to keep";
      };

      incrementalDays = mkOption {
        type = types.int;
        default = 30;
        description = "Days to keep incremental rsync backups";
      };
    };
  };

  config = mkIf cfg.enable {
    # Install required backup tools
    environment.systemPackages = with pkgs; [
      rsync # File synchronization
      jq # JSON processing for manifests
      gzip # Compression
      gnutar # Archive management
      coreutils # Essential utilities
      findutils # File finding
      util-linux # System utilities
      wslu # WSL utilities (wslpath)
      powershell # Windows notifications
    ];

    # Create backup log directory
    systemd.tmpfiles.rules = [
      "d /var/log/backup 0755 root root -"
    ];

    # Systemd timer for automatic backups (optional)
    systemd.services.wsl-backup = mkIf cfg.schedule.enable {
      description = "WSL NixOS Backup Service";
      wants = ["network-online.target"];
      after = ["network-online.target"];

      serviceConfig = {
        Type = "oneshot";
        ExecStart = "${cfg.scripts.wslBackup} backup";
        User = "root";
        StandardOutput = "journal";
        StandardError = "journal";
      };
    };

    systemd.timers.wsl-backup = mkIf cfg.schedule.enable {
      description = "WSL NixOS Backup Timer";
      wantedBy = ["timers.target"];

      timerConfig = {
        OnCalendar = cfg.schedule.frequency;
        Persistent = true;
        Unit = "wsl-backup.service";
      };
    };

    # Backup configuration file
    environment.etc."backup/wsl-backup.conf" = {
      text = ''
        # WSL Backup Configuration
        # Generated by NixOS configuration

        BACKUP_DIR_WINDOWS="${cfg.backupDir}"
        KEEP_FULL_BACKUPS=${toString cfg.retention.fullBackups}
        KEEP_INCREMENTAL_DAYS=${toString cfg.retention.incrementalDays}
        ENABLE_NOTIFICATIONS=true
        VERIFY_BACKUPS=true
        USE_COMPRESSION=true
        COMPRESSION_LEVEL=6
      '';
      mode = "0644";
    };

    # Create convenient backup aliases
    environment.shellAliases = {
      wsl-backup = "${cfg.scripts.wslBackup} backup";
      wsl-restore = "${cfg.scripts.wslBackup} restore";
      wsl-backup-verify = "${cfg.scripts.wslBackup} verify";
    };
  };
}
