{
  config,
  lib,
  pkgs,
  ...
}:
with lib; let
  cfg = config.modules.system.backup;
in {
  options.modules.system.backup = {
    enable = mkEnableOption "system backup configuration";

    scripts = {
      wslBackup = mkOption {
        type = types.path;
        default = ../../tools/scripts/wsl-backup-hpprobook.sh;
        description = "Path to WSL backup script";
      };

      powershellOrchestrator = mkOption {
        type = types.path;
        default = ../../tools/scripts/WSL-Backup-Orchestrator.ps1;
        description = "Path to PowerShell orchestration script";
      };
    };

    schedule = {
      enable = mkEnableOption "automatic backup scheduling via systemd timer";

      frequency = mkOption {
        type = types.str;
        default = "daily";
        description = "Backup frequency (systemd timer format)";
      };

      time = mkOption {
        type = types.str;
        default = "02:00";
        description = "Time to run backup (HH:MM format)";
      };
    };

    backupDir = mkOption {
      type = types.str;
      default = "D:/Backups/WSL-NixOS";
      description = "Backup destination directory (Windows path)";
    };

    retention = {
      fullBackups = mkOption {
        type = types.int;
        default = 3;
        description = "Number of full VHDX exports to keep";
      };

      incrementalDays = mkOption {
        type = types.int;
        default = 30;
        description = "Days to keep incremental rsync backups";
      };
    };
  };

  config = mkIf cfg.enable {
    # Install required backup tools
    environment.systemPackages = with pkgs; [
      rsync # File synchronization
      jq # JSON processing for manifests
      gzip # Compression
      gnutar # Archive management
      coreutils # Essential utilities
      findutils # File finding
      util-linux # System utilities
      wslu # WSL utilities (wslpath)
      powershell # Windows notifications
    ];

    # Create backup log directory
    systemd.tmpfiles.rules = [
      "d /var/log/backup 0755 root root -"
    ];

    # Systemd timer for automatic backups (optional)
    systemd.services.wsl-backup = mkIf cfg.schedule.enable {
      description = "WSL NixOS Backup Service";
      wants = ["network-online.target"];
      after = ["network-online.target"];

      serviceConfig = {
        Type = "oneshot";
        ExecStart = "${cfg.scripts.wslBackup} backup";
        User = "root";
        StandardOutput = "journal";
        StandardError = "journal";
      };
    };

    systemd.timers.wsl-backup = mkIf cfg.schedule.enable {
      description = "WSL NixOS Backup Timer";
      wantedBy = ["timers.target"];

      timerConfig = {
        OnCalendar = cfg.schedule.frequency;
        Persistent = true;
        Unit = "wsl-backup.service";
      };
    };

    # Backup configuration file
    environment.etc."backup/wsl-backup.conf" = {
      text = ''
        # WSL Backup Configuration
        # Generated by NixOS configuration

        BACKUP_DIR_WINDOWS="${cfg.backupDir}"
        KEEP_FULL_BACKUPS=${toString cfg.retention.fullBackups}
        KEEP_INCREMENTAL_DAYS=${toString cfg.retention.incrementalDays}
        ENABLE_NOTIFICATIONS=true
        VERIFY_BACKUPS=true
        USE_COMPRESSION=true
        COMPRESSION_LEVEL=6
      '';
      mode = "0644";
    };

    # Create convenient backup aliases
    environment.shellAliases = {
      wsl-backup = "${cfg.scripts.wslBackup} backup";
      wsl-restore = "${cfg.scripts.wslBackup} restore";
      wsl-backup-verify = "${cfg.scripts.wslBackup} verify";
    };

    # Emergency recovery documentation
    environment.etc."backup/README.md" = {
      text = ''
        # WSL Backup System

        ## Quick Start

        ### Running Backups

        From WSL:
        ```bash
        sudo wsl-backup                  # Run full backup
        sudo wsl-backup-verify           # Verify backup integrity
        ```

        From Windows PowerShell (recommended):
        ```powershell
        # Full backup (export + incremental)
        powershell -ExecutionPolicy Bypass -File C:\path\to\WSL-Backup-Orchestrator.ps1

        # Incremental only (skip export)
        powershell -ExecutionPolicy Bypass -File C:\path\to\WSL-Backup-Orchestrator.ps1 -SkipExport

        # Restore mode
        powershell -ExecutionPolicy Bypass -File C:\path\to\WSL-Backup-Orchestrator.ps1 -Mode Restore
        ```

        ### Backup Locations

        Backups are stored in: `${cfg.backupDir}`

        Structure:
        - `full/` - Complete WSL distribution exports (.tar files)
        - `incremental/` - Daily rsync snapshots
        - `nix-metadata/` - Nix store metadata and generation info

        ### Restore Operations

        1. **Full WSL Restore** (from Windows):
           ```powershell
           wsl --unregister NixOS
           wsl --import NixOS C:\WSL\NixOS D:\Backups\WSL-NixOS\full\NixOS_TIMESTAMP.tar
           ```

        2. **Incremental File Restore** (from WSL):
           ```bash
           sudo wsl-restore
           # Follow interactive prompts
           ```

        3. **Manual File Restore**:
           ```bash
           sudo rsync -aAXv /path/to/backup/incremental/YYYYMMDD/ /
           ```

        ## Configuration

        Backup settings: `/etc/backup/wsl-backup.conf`

        Edit these in your NixOS configuration:
        ```nix
        modules.system.backup = {
          enable = true;
          backupDir = "D:/Backups/WSL-NixOS";
          retention = {
            fullBackups = 3;
            incrementalDays = 30;
          };
        };
        ```

        ## Scheduling

        ### Windows Task Scheduler (Recommended)

        1. Open Task Scheduler
        2. Create Basic Task
        3. Trigger: Daily at 2:00 AM
        4. Action: Start a program
           - Program: `powershell.exe`
           - Arguments: `-ExecutionPolicy Bypass -File "C:\path\to\WSL-Backup-Orchestrator.ps1"`
        5. Conditions: Only if computer is on AC power
        6. Settings: Allow task to run on demand

        ### WSL Systemd Timer (Alternative)

        Enable in NixOS configuration:
        ```nix
        modules.system.backup.schedule = {
          enable = true;
          frequency = "daily";
          time = "02:00";
        };
        ```

        Note: Requires WSL to be running at scheduled time.

        ## Security Considerations

        1. **Encryption**: Use BitLocker/VeraCrypt for backup drive
        2. **Access Control**: Restrict backup directory permissions
        3. **Off-site Backups**: Copy to cloud/network storage
        4. **Testing**: Regularly test restore procedures
        5. **Secrets**: Ensure sops-age keys are backed up separately

        ## Monitoring

        - Check logs: `/var/log/backup/wsl-backup.log`
        - Windows notifications on completion/failure
        - PowerShell logs: `$env:TEMP\WSL-Backup-Logs`

        ## Troubleshooting

        ### Backup Script Not Found
        ```bash
        ls -la ${cfg.scripts.wslBackup}
        ```

        ### Permission Denied
        ```bash
        sudo chmod +x ${cfg.scripts.wslBackup}
        ```

        ### WSL Export Fails
        - Ensure sufficient disk space
        - Close all WSL terminals
        - Run from elevated PowerShell

        ### Rsync Errors
        ```bash
        # Check rsync version
        rsync --version

        # Test connectivity to backup location
        ls $(wslpath '${cfg.backupDir}')
        ```

        For more details, see: https://github.com/FelixSchausberger/nixos/wiki/Backup-and-Recovery
      '';
      mode = "0644";
    };
  };
}
