name: Auto Merge
on:
  pull_request:
    types: [labeled, synchronize, opened, reopened]
permissions:
  contents: write
  pull-requests: write
jobs:
  auto-merge:
    name: Enable Auto-Merge
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'auto-merge')
    steps:
      - name: Enable auto-merge for PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          echo "🔄 Enabling auto-merge for PR #$PR_NUMBER"
          gh pr merge --auto --merge "$PR_NUMBER" --repo "$REPO"
          echo "✅ Auto-merge enabled - PR will merge automatically when all checks pass"
